### ISSUE TITLE
Unable to find the "processed" folder

### ISSUE THREAD

**Issue by xubingze** [Graph-COM/Neighborhood-Aware-Temporal-Network#3]
Hi, I would like to take a look a the input data and try to run it with SocialEvolve data, but I cannot find the corresponding folder or dataset. Can you help me with this issue? Thank you very much!

**Comment by JamesLuoyh** [comment]
You can download the datasets from [here](https://drive.google.com/drive/folders/1umS1m1YbOM10QOyVbGwtXrsiK3uTD7xQ).
