### ISSUE TITLE
Why feed the 2-hop N-caches into RNN?

### ISSUE THREAD

**Issue by lxd99** [Graph-COM/Neighborhood-Aware-Temporal-Network#5]
Thanks for your great work! I find that in your implementation, the 2-hop n-caches will be feed into the RNN when obtained by the function of batch_fetch_ncaches, which is https://github.com/Graph-COM/Neighborhood-Aware-Temporal-Network/blob/a05483156b4b0d601fd23abbbca07d1b541610f7/module.py#L315-L331 However, in your original paper, the 2-hop n-caches is the copy of neighbors' one-hop n-caches (line 11 of Algorithmn 1),which is  ![1](https://github.com/Graph-COM/Neighborhood-Aware-Temporal-Network/assets/43784165/6c83b62b-d16f-42e3-9276-1658f3c16915) Thus, the updating of the 2-hop n-caches seems inconsistent with the original paper. Do I miss some key points? Looking forward for you reply！

**Comment by JamesLuoyh** [comment]
Hi there, thanks for the question. If I understand right, you have question about why we pass the 2-nd hop neighborhood representation into ngh_aggregator which runs RNNs (line 325 in your screenshot).

The answer is although the value of the updated_self_rep is returned, it is never used afterward. The batch_fetch_ncaches is an abstraction for fetching the relevant features from 0-2 hops but the return values are not used the same way. For 0-1 hops, the updated_self_rep returned will be used for updating the 0-1 hop N-caches but for the 2 hop, it is not.

If there are further questions, feel free to send an email to the first author. This repo does not send a notification to us for issues.
